name: youbike_potential_demand
channels:
  - conda-forge
  - defaults
dependencies:
  - catboost=1.2
  - geopandas=0.13.2
  - lightgbm=3.3.5
  - matplotlib=3.7.1
  - numpy=1.23.3
  - optuna=3.2.0
  - pandas=2.0.3
  - pickleshare=0.7.5
  - plotly=5.9.0
  - pre-commit=3.4.0
  - pykml=0.2.0
  - python=3.9.18
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - shapely=2.0.1
  - tqdm=4.65.0
  - xgboost=1.7.6
  - rasterio=1.3.8
  - rasterstats=0.19.0
  - scikit-image=0.21.0
